//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XingSub {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizable() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XingSub.Localizable", typeof(Localizable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 File is changed. Do you want to save it? 的本地化字符串。
        /// </summary>
        internal static string AskToSaveMessage {
            get {
                return ResourceManager.GetString("AskToSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save File 的本地化字符串。
        /// </summary>
        internal static string AskToSaveTitle {
            get {
                return ResourceManager.GetString("AskToSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto saved: {0} 的本地化字符串。
        /// </summary>
        internal static string AutoSaved {
            get {
                return ResourceManager.GetString("AutoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration file may be damage. Restored. 的本地化字符串。
        /// </summary>
        internal static string ConfigWarningMessage {
            get {
                return ResourceManager.GetString("ConfigWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effects mode 的本地化字符串。
        /// </summary>
        internal static string EffectsMode {
            get {
                return ResourceManager.GetString("EffectsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}|*.{1}|All Files(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string ExportFileType {
            get {
                return ResourceManager.GetString("ExportFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtitles exported successfully. 的本地化字符串。
        /// </summary>
        internal static string ExportSussessMessage {
            get {
                return ResourceManager.GetString("ExportSussessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export subtitles 的本地化字符串。
        /// </summary>
        internal static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This plugin has a major version number different from its host.
        ///For avoiding errors leading by interface upgrade, plugin needs a major version number as same as its host program.
        ///
        ///Currect version: {0} 的本地化字符串。
        /// </summary>
        internal static string FailedToLoadPluginMessage {
            get {
                return ResourceManager.GetString("FailedToLoadPluginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skipped Loading Plugin: {0} 的本地化字符串。
        /// </summary>
        internal static string FailedToLoadPluginTitle {
            get {
                return ResourceManager.GetString("FailedToLoadPluginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inserted time stamp: {0} 的本地化字符串。
        /// </summary>
        internal static string InsertedTimeStamp {
            get {
                return ResourceManager.GetString("InsertedTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There may be something wrong with your styles text modified just now.
        ///
        ///Please correct it then try again. 的本地化字符串。
        /// </summary>
        internal static string InvaildStyles {
            get {
                return ResourceManager.GetString("InvaildStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invaild styles 的本地化字符串。
        /// </summary>
        internal static string InvaildStylesTitle {
            get {
                return ResourceManager.GetString("InvaildStylesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New File 的本地化字符串。
        /// </summary>
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal mode 的本地化字符串。
        /// </summary>
        internal static string NormalMode {
            get {
                return ResourceManager.GetString("NormalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supports Files(*.xss;*.xse;*.ass;*.txt)|*.xss;*.xse;*.ass;*.txt|XingSub Subtitles Timeline(*.xss)|*.xss|XingSub Effects Timeline(*.xse)|*.xse|Advanced SubStation Alpha(*.ass)|*.ass|Text File(*.txt)|*.txt|All Files(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string OpenFileType {
            get {
                return ResourceManager.GetString("OpenFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        internal static string OpenTitle {
            get {
                return ResourceManager.GetString("OpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XingSub Subtitles Timeline(*.xss)|*.xss|XingSub Effects Timeline(*.xse)|*.xse|All Files(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string SaveAsFileType {
            get {
                return ResourceManager.GetString("SaveAsFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XingSub Effects Timeline(*.xse)|*.xse|All Files(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string SaveEffectsFileType {
            get {
                return ResourceManager.GetString("SaveEffectsFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save XingSub Effects Timeline 的本地化字符串。
        /// </summary>
        internal static string SaveEffectsTitle {
            get {
                return ResourceManager.GetString("SaveEffectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XingSub Subtitles Timeline(*.xss)|*.xss|All Files(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string SaveSubtitlesFileType {
            get {
                return ResourceManager.GetString("SaveSubtitlesFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save XingSub Subtitles Timeline 的本地化字符串。
        /// </summary>
        internal static string SaveSubtitlesTitle {
            get {
                return ResourceManager.GetString("SaveSubtitlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XingSub - {0} [{1}] 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
